version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: gestao-eventos-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ../gestao-eventos-backend
    container_name: gestao-eventos-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db_net
      - front_net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 4

  frontend:
    build:
      context: ../gestao-eventos-front
      dockerfile: Dockerfile
    container_name: gestao-eventos-front
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - front_net

networks:
  db_net:
    driver: bridge
  front_net:
    driver: bridge

volumes:
  postgres_data: